version: '2' # specify docker-compose version
# Define the services/containers to be run
services:
  frontend: #name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "80:4200" # specify port forewarding
    #container_name: Classes-container
    #restart: always
  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
                                                                                                                                                                                                                                                                                                                                                                                                                            
